apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keydb
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: keydb
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: keydb
        namespace: flux-system
  values:
    replicaCount: 1
    auth:
      enabled: true
      existingSecret: ""
    persistence:
      enabled: true
      size: 1Gi
    service:
      type: ClusterIP
      port: 6379
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
