apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - minio/helm-release.yaml

configMapGenerator:
  - name: minio-dashboards
    files:
      - minio/dashboards/minio-overview.json

commonLabels:
  app.kubernetes.io/component: storage
