apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: search
spec:
  interval: 5m
  chart:
    spec:
      chart: searxng
      version: "5.3.2"
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system
  values:
    image:
      repository: searxng/searxng
      tag: latest
    env:
      - name: BASE_URL
        value: "https://search.jkittell.com"
      - name: INSTANCE_NAME
        value: "Personal Search"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: search.jkittell.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - search.jkittell.com
            secretName: searxng-tls
    persistence:
      config:
        enabled: true
        mountPath: /etc/searxng
        type: configMap
        name: searxng-settings
