apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: search
spec:
  interval: 5m
  chart:
    spec:
      chart: searxng
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system
  values:
    searxng:
      config:
        server:
          base_url: https://search.jkittell.com
          secret_key: ${SEARXNG_SECRET_KEY:-changeme}
          bind_address: "0.0.0.0:8080"
        general:
          instance_name: "Personal Search"
          debug: false
    
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: search.jkittell.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - search.jkittell.com
          secretName: searxng-tls
    
    service:
      type: ClusterIP
      port: 8080
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 512Mi
