apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: search
spec:
  interval: 5m
  chart:
    spec:
      chart: searxng
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system
  values:
    image:
      repository: searxng/searxng
      tag: latest
    
    # Add volume for configuration
    volumes:
      - name: config-volume
        emptyDir: {}
    
    volumeMounts:
      - name: config-volume
        mountPath: /etc/searxng
    
    env:
      - name: BASE_URL
        value: "https://search.${DOMAIN}"
      - name: INSTANCE_NAME
        value: "Personal Search"
    
    service:
      type: ClusterIP
      port: 8080
    
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    
    ingress:
      enabled: false  # We'll use our own ingress configuration
