apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: search
spec:
  interval: 5m
  chart:
    spec:
      chart: searxng
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system
  values:
    image:
      repository: searxng/searxng
      tag: latest
    
    # Add volume for configuration
    volumes:
      - name: config-volume
        emptyDir: {}
      - name: settings
        configMap:
          name: searxng-config
    
    volumeMounts:
      - name: config-volume
        mountPath: /etc/searxng
      - name: settings
        mountPath: /etc/searxng/settings.yml
        subPath: settings.yml
    
    env:
      - name: BASE_URL
        value: "https://search.jkittell.com"
      - name: INSTANCE_NAME
        value: "Personal Search"
    
    service:
      main:
        ports:
          http:
            port: 8080
            enabled: true
        type: ClusterIP
    
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    
    ingress:
      main:
        enabled: true
        hosts:
          - host: search.jkittell.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - search.jkittell.com
