apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: search
spec:
  interval: 5m
  chart:
    spec:
      chart: ./searxng
      sourceRef:
        kind: GitRepository
        name: searxng
        namespace: flux-system
  values:
    image:
      repository: searxng/searxng
      tag: latest
    
    config:
      baseUrl: "https://search.jkittell.com"
      instanceName: "Personal Search"
      redis:
        host: keydb
        port: 6379
    
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: search.jkittell.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - search.jkittell.com
          secretName: searxng-tls
