apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sources.yaml
  - cert-manager  # SSL certificates
  - database    # CrateDB and KeyDB
  - storage     # MinIO
  - monitoring  # Prometheus, Grafana, etc.
  - ingress     # Nginx Ingress
  - search      # SearXNG
  - GitRepository

patches:
  - path: patches/env.yaml
    target:
      kind: HelmRelease

commonLabels:
  app.kubernetes.io/managed-by: flux