apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sources.yaml
  - database    # CrateDB and KeyDB
  - storage     # MinIO
  - monitoring  # Prometheus, Grafana, etc.
  - ingress     # Nginx Ingress
  - search      # SearXNG