apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
  postBuild:
    substitute:
      # Cloud settings
      ENVIRONMENT: cloud
      DOMAIN: ${DROPLET_IP}.nip.io  # Will automatically map to your Droplet's IP
      # DigitalOcean resources
      MINIO_STORAGE: "20Gi"
