apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml
  - helm-release.yaml
  - cluster-issuer.yaml

commonLabels:
  app.kubernetes.io/part-of: tech-stack
  app.kubernetes.io/component: cert-manager
